Ce manuel est en évolution permanente. Si vous voulez nous aider à 
son écriture, sa rédaction, sa traduction ou la préparation des 
graphiques, merci de contactez n'importe quel membre de l'équipe 
de traduction ou envoyez un courrier électronique à 
emc-users@lists.sourceforge.net.

    Copyright © 2000-2021 LinuxCNC.org

Permission is granted to copy, distribute and/or modify this 
document under the terms of the GNU Free Documentation License, 
Version 1.3 or any later version published by the Free Software 
Foundation; with no Invariant Sections, no Front-Cover Texts, and 
no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU 
Free Documentation License"..
If you do not find the license you may order a copy from:

 Free Software Foundation, Inc.
 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

LINUX® is the registered trademark of Linus Torvalds in the U.S. 
and other countries. The registered trademark Linux® is used pursuant 
to a sublicense from LMI, the exclusive licensee of Linus Torvalds, 
owner of the mark on a world-wide basis.

Permission est donnée de copier, distribuer et/ou modifier ce 
document selon les termes de la « GNU Free Documentation License », 
Version 1.1 ou toute version ultérieure publiée par la « Free 
Software Foundation »; sans sections inaltérables, sans texte de 
couverture, ni quatrième de couverture. Une copie de la licence est 
incluse dans la section intitulée 
xref:gpld-copyright_fr.adoc#gpld[« GNU Free Documentation License »]. 
Si vous ne trouvez pas la licence vous pouvez en commander un 
exemplaire chez:

 Free Software Foundation, Inc. 
 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

LINUX® est une marque déposée de Linus Torvalds aux États Unis 
d'Amérique et dans les autres pays. La marque déposée Linux® est
utilisée conformément à une sous licence de LMI, le licencié exclusif
de Linus Torvalds, détendeur de la marque mondiale.

Le projet LinuxCNC n'est pas affilié avec Debian®.
_Debian_ est une marque déposée détenue par Software in the Public 
Interest, Inc.

Le projet LinuxCNC n'est pas affilié avec UBUNTU®.
_UBUNTU_ est une marque déposée détenue par Canonical Limited.

[NOTE]
====
La version de langue anglaise fait foi
====


